spring.application.name=pitsdog-api

spring.datasource.url=jdbc:postgresql://localhost:5432/pitsdog_db
spring.datasource.username=postgres
spring.datasource.password=xz199yA@#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true